#!/sbin/runscript
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend()
{
	need net
}

start()
{
	ebegin "Starting babeld"

	/usr/sbin/babeld -I ${BABELD_PID_FILE} ${BABELD_EXTRA_OPTS}

	eend $?
}

stop()
{
	ebegin "Starting babeld"

	pid=$(cat ${BABELD_PID_FILE})
	ps ${pid} | grep -q babeld && kill ${pid} 

	eend $?
}

restart()
{
	svc_stop
	sleep 3
	svc_start
}
